title: Gordan Bezjak  # your name (or website title) here
logo: "/images/ProfilePicture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Game Developer in Unity
  .NET Programmer
  <br><br>
  Professor of Croatian Studies
  Professor of Classical Studies
  <br><br>
  Musician
  Amateur Actor
  Poet
  Caver
  Hiker
  Gamer
  Swing Jazz Dancer
  Dean's Award Winner
  Global Game Jam Third Runner Up
  
  and many more...
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
