title: Gordan Bezjak  # your name (or website title) here
logo: "/images/ProfilePicture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Game Developer in Unity <br>
  .NET Programmer
  <br><br>
  Professor of Croatian Studies <br>
  Professor of Classical Studies 
  <br><br>
  Musician <br>
  Amateur Actor <br>
  Poet <br>
  Caver <br>
  Hiker <br>
  Gamer <br>
  Swing Jazz Dancer <br>
  Dean's Award Winner <br>
  Global Game Jam Third Runner Up <br>
  <br>
  and many more...
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
